// <auto-generated />
using System;
using ExamCorrection.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamCorrection.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260212093944_AddStudentExamPaperColumns")]
    partial class AddStudentExamPaperColumns
    {
        /// <inheritdoc />
    }
}
